### ISSUE TITLE
Unaligned transfer on the DMA interface for the application block

### ISSUE THREAD

**Issue by KireinaHoro** [corundum/corundum#160]
I'm trying to issue unaligned transfers on the DMA interface over PCIe, to match the semantics of AXI strobed writes from my application logic.  I am currently using `dma_client_axis_sink.v`, which seems to process `TKEEP`; however, the segmented DMA interface does not have byte enable signals on the descriptor.  Does the DMA subsystem support strobed writes?

**Comment by alexforencich** [comment]
PCIe does not support that outside of the first and last dword in each request TLP, so the DMA engine does not support it.  And incidentally this is the main reason I haven't written an AXI slave DMA client yet; converting the byte enables to DMA operations is not so straightforward since you have to interpret the byte enables to extract contiguous blocks and issue a separate DMA transfer request for every block, even if it's only 1 byte.  

I guess maybe it could be possible to add a way to specify the byte enables in some way, but the semantics for how that might work get a bit tricky.  Perhaps if we limit it to only 32 bit writes that might be reasonable to implement.  But either way, you would still have to slice and dice each transfer into a bunch of separate DMA operations, it just might reduce the number of DMA operations that you need when you get a really strange set of byte enables.

**Comment by KireinaHoro** [comment]
Thanks for the information!  I think at the moment what I need is just unaligned but contiguous transfers instead of arbitrary byte-enable configurations.  As you said that the PCIe TLP format allows for a byte-enable on the first and last dword, that should in theory allow for unaligned transfers.  Does the Corundum DMA subsystem support this, for example if I issue unaligned requests onto the descriptor bus?

To explain my current semantics a bit better:
- in software running on my application block, we issue unaligned DMA transfers (suppose 64B alignment requirements, so `addr % 0x40 == 0`):
  `write 40B to 0xffffffff00000030`
- the requests arrive on AXI as
  `write to 0xffffffff00000000 strobe=0xff000000`
  `write to 0xffffffff00000040 strobe=0xfff`
- my bridge module captures the data in scratch SRAM
- my bridge module issues to Corundum:
  `write to 0xffffffff00000000, len=128`
- data at `0xffffffff00000000-0xffffffff00000030` and `0xffffffff00000058-0xffffffff00000080` are overwritten

Could I, in this situation, issue a `write to 0xffffffff000030, len=40` directly?

**Comment by alexforencich** [comment]
Yes, the DMA interface supports fully unaligned transfers.
